name: 'Redocly Reunite Push'
description: 'Action for pushing files to Redocly Reunite app'
author: 'Redocly'

branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  organization:
    description: 'Redocly organization slug'
    required: true
  project:
    description: 'Redocly project slug'
    required: true
  domain:
    description: 'Redocly app domain'
    required: false
  files:
    description: 'Space separated list of files/folders to push'
    required: true
  mountPath:
    description: 'Remote content mount path inside target Redocly project'
    required: true
  maxExecutionTime:
    description: 'Max execution time in seconds'
    required: false
  redoclyConfigPath:
    description: 'Path to the redocly config file'
    required: false
  githubToken:
    description: 'Token to authenticate with'
    required: true
    default: ${{ github.token }}

outputs:
  pushId:
    description: 'Push ID'

runs:
  using: node20
  main: dist/index.js
